/**
 * Symbeon Mission Control - MCP Server (Phase 5)
 * Implements MCS-0004 (Mission Control Protocol)
 * Provides stdio JSON-RPC 2.0 MCP interface for AI Agents
 */

import fs from 'fs';
import path from 'path';
import readline from 'readline';
import { fileURLToPath } from 'url';

import { GraphManager } from '../src/js/graph/GraphManager.js';
import { LiveGovernance } from '../src/js/governance/LiveGovernance.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, '..');
const PROJECT_ID = 'guarddrive';
const STORAGE_DIR = path.join(ROOT_DIR, 'storage', 'projects', PROJECT_ID);

// Initialize Graph and LiveGovernance
const graphManager = new GraphManager();
const liveGovernance = new LiveGovernance(graphManager);

// Data store
let projectData = {};

function loadProjectData() {
  const files = ['tasks', 'milestones', 'decisions', 'documents', 'evidence', 'releases', 'risk'];
  const data = [];

  for (const file of files) {
    const filePath = path.join(STORAGE_DIR, `${file}.json`);
    if (fs.existsSync(filePath)) {
      try {
        const json = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
        const items = json[file] || json.tasks || json.risks || [];
        const typeName = file.charAt(0).toUpperCase() + file.slice(1).replace(/s$/, '');
        
        items.forEach(item => {
          data.push({
            ...item,
            type: item.type || typeName
          });
        });
        projectData[file] = json;
      } catch (err) {
        console.error(`Error loading ${file}.json:`, err.message);
      }
    }
  }

  liveGovernance.initialize(data);
}

// Initial load
loadProjectData();

// Define Available MCP Tools based on MCS-0004
const TOOLS = [
  {
    name: 'mc_get_governance_state',
    description: 'Returns overall Governance Score, Maturity Level, active Violations, and Policy Compliance Rate for the project.',
    inputSchema: {
      type: 'object',
      properties: {
        projectId: { type: 'string', description: 'ID of the project (default: guarddrive)' }
      }
    }
  },
  {
    name: 'mc_evaluate_policies',
    description: 'Executes the PolicyEngine to detect ALM violations and check compliance against Architectural Laws.',
    inputSchema: {
      type: 'object',
      properties: {}
    }
  },
  {
    name: 'mc_get_recommendations',
    description: 'Returns recommendations generated by the RecommendationEngine to improve project maturity.',
    inputSchema: {
      type: 'object',
      properties: {}
    }
  },
  {
    name: 'mc_create_operational_object',
    description: 'Creates a new OperationalObject (Task, Decision, Document, Milestone, Release, Risk).',
    inputSchema: {
      type: 'object',
      properties: {
        type: { type: 'string', description: 'Object type (Task, Decision, Document, Milestone, Release, Risk)' },
        title: { type: 'string', description: 'Title of the object' },
        description: { type: 'string', description: 'Detailed description' },
        owner: { type: 'string', description: 'Responsible entity or agent' },
        status: { type: 'string', description: 'Initial status (default: draft)' }
      },
      required: ['type', 'title']
    }
  },
  {
    name: 'mc_relate_objects',
    description: 'Creates a typed relation edge between two OperationalObjects in the graph.',
    inputSchema: {
      type: 'object',
      properties: {
        sourceId: { type: 'string', description: 'ID of the source object' },
        targetId: { type: 'string', description: 'ID of the target object' },
        relationType: { type: 'string', description: 'Relation type (e.g., CREATES, BELONGS_TO, PROVES, APPROVES, DEPENDS_ON)' },
        sourceType: { type: 'string', description: 'Type of source object' },
        targetType: { type: 'string', description: 'Type of target object' }
      },
      required: ['sourceId', 'targetId', 'relationType']
    }
  },
  {
    name: 'mc_submit_evidence',
    description: 'Attaches verifiable Evidence to an OperationalObject (Enforces LAW-0003: Evidence Precedes Truth).',
    inputSchema: {
      type: 'object',
      properties: {
        targetObjectId: { type: 'string', description: 'ID of the object to prove (e.g. TASK-001)' },
        evidenceType: { type: 'string', description: 'Type of evidence (Commit, PullRequest, Document, Meeting, TestRun)' },
        title: { type: 'string', description: 'Title of the evidence' },
        sourceUrl: { type: 'string', description: 'URL or path to the evidence artifact' }
      },
      required: ['targetObjectId', 'evidenceType', 'title']
    }
  }
];

// Execute MCP Tool Handler
function handleToolCall(name, args) {
  switch (name) {
    case 'mc_get_governance_state': {
      const data = liveGovernance.getDashboardData();
      return { content: [{ type: 'text', text: JSON.stringify(data, null, 2) }] };
    }
    case 'mc_evaluate_policies': {
      const state = liveGovernance.getCurrentState();
      return { content: [{ type: 'text', text: JSON.stringify(state.violations, null, 2) }] };
    }
    case 'mc_get_recommendations': {
      const state = liveGovernance.getCurrentState();
      return { content: [{ type: 'text', text: JSON.stringify(state.recommendations, null, 2) }] };
    }
    case 'mc_create_operational_object': {
      const newObj = {
        id: `${args.type.toUpperCase()}-${Date.now().toString().slice(-4)}`,
        type: args.type,
        title: args.title,
        description: args.description || '',
        owner: args.owner || 'Agent',
        status: args.status || 'draft',
        created_at: new Date().toISOString()
      };
      
      liveGovernance.onObjectModified(newObj.id, newObj.type, newObj.owner);
      return { content: [{ type: 'text', text: JSON.stringify({ message: 'Object created successfully', object: newObj }, null, 2) }] };
    }
    case 'mc_relate_objects': {
      const relation = graphManager.createRelation(
        args.sourceId,
        args.targetId,
        args.sourceType || 'Task',
        args.targetType || 'Milestone',
        args.relationType,
        'Agent'
      );
      liveGovernance.onGraphModified(relation.id, 'create', 'Agent');
      return { content: [{ type: 'text', text: JSON.stringify({ message: 'Relation created', relation }, null, 2) }] };
    }
    case 'mc_submit_evidence': {
      const evidenceId = `EVD-${Date.now().toString().slice(-4)}`;
      const relation = graphManager.createRelation(
        args.targetObjectId,
        evidenceId,
        'Task',
        'Evidence',
        'PROVES',
        'Agent',
        { sourceUrl: args.sourceUrl, type: args.evidenceType, title: args.title }
      );
      liveGovernance.onGraphModified(relation.id, 'create', 'Agent');
      return { content: [{ type: 'text', text: JSON.stringify({ message: 'Evidence attached and verified', evidenceId, relation }, null, 2) }] };
    }
    default:
      throw new Error(`Unknown tool: ${name}`);
  }
}

// JSON-RPC stdio Handler
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
  terminal: false
});

rl.on('line', (line) => {
  if (!line.trim()) return;
  try {
    const request = JSON.parse(line);
    const { id, method, params } = request;

    if (method === 'initialize') {
      sendResponse(id, {
        protocolVersion: '2024-11-05',
        capabilities: { tools: {} },
        serverInfo: { name: 'symbeon-mission-control', version: '1.0.0' }
      });
    } else if (method === 'notifications/initialized') {
      // Acknowledged
    } else if (method === 'tools/list') {
      sendResponse(id, { tools: TOOLS });
    } else if (method === 'tools/call') {
      const result = handleToolCall(params.name, params.arguments || {});
      sendResponse(id, result);
    } else {
      sendError(id, -32601, `Method not found: ${method}`);
    }
  } catch (err) {
    sendError(null, -32700, `Parse error: ${err.message}`);
  }
});

function sendResponse(id, result) {
  const msg = JSON.stringify({ jsonrpc: '2.0', id, result });
  process.stdout.write(msg + '\n');
}

function sendError(id, code, message) {
  const msg = JSON.stringify({ jsonrpc: '2.0', id, error: { code, message } });
  process.stdout.write(msg + '\n');
}
